# Generated by Django 5.1.2 on 2025-01-10 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookatable',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=15),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
