# Generated by Django 5.1.2 on 2025-01-10 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_bookatable_date_bookatable_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='bookatable',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='bookatable',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
