# Generated by Django 5.1.2 on 2025-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_bookatable_date_alter_bookatable_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookatable',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='bookatable',
            old_name='time',
            new_name='booking_time',
        ),
        migrations.RenameField(
            model_name='bookatable',
            old_name='number_of_guests',
            new_name='guest_count',
        ),
        migrations.RenameField(
            model_name='bookatable',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='bookatable',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
